p8105_hw1_nn2477
================
Nhu Nguyen
2023-09-15

**Problem 1**

``` r
library(tidyverse)
```

    ## ── Attaching core tidyverse packages ──────────────────────── tidyverse 2.0.0 ──
    ## ✔ dplyr     1.1.3     ✔ readr     2.1.4
    ## ✔ forcats   1.0.0     ✔ stringr   1.5.0
    ## ✔ ggplot2   3.4.3     ✔ tibble    3.2.1
    ## ✔ lubridate 1.9.2     ✔ tidyr     1.3.0
    ## ✔ purrr     1.0.2     
    ## ── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
    ## ✖ dplyr::filter() masks stats::filter()
    ## ✖ dplyr::lag()    masks stats::lag()
    ## ℹ Use the conflicted package (<http://conflicted.r-lib.org/>) to force all conflicts to become errors

``` r
library("moderndive")
data("early_january_weather")

#finding the variables in data set
names(early_january_weather)
```

    ##  [1] "origin"     "year"       "month"      "day"        "hour"      
    ##  [6] "temp"       "dewp"       "humid"      "wind_dir"   "wind_speed"
    ## [11] "wind_gust"  "precip"     "pressure"   "visib"      "time_hour"

``` r
early_january_weather
```

    ## # A tibble: 358 × 15
    ##    origin  year month   day  hour  temp  dewp humid wind_dir wind_speed
    ##    <chr>  <int> <int> <int> <int> <dbl> <dbl> <dbl>    <dbl>      <dbl>
    ##  1 EWR     2013     1     1     1  39.0  26.1  59.4      270      10.4 
    ##  2 EWR     2013     1     1     2  39.0  27.0  61.6      250       8.06
    ##  3 EWR     2013     1     1     3  39.0  28.0  64.4      240      11.5 
    ##  4 EWR     2013     1     1     4  39.9  28.0  62.2      250      12.7 
    ##  5 EWR     2013     1     1     5  39.0  28.0  64.4      260      12.7 
    ##  6 EWR     2013     1     1     6  37.9  28.0  67.2      240      11.5 
    ##  7 EWR     2013     1     1     7  39.0  28.0  64.4      240      15.0 
    ##  8 EWR     2013     1     1     8  39.9  28.0  62.2      250      10.4 
    ##  9 EWR     2013     1     1     9  39.9  28.0  62.2      260      15.0 
    ## 10 EWR     2013     1     1    10  41    28.0  59.6      260      13.8 
    ## # ℹ 348 more rows
    ## # ℹ 5 more variables: wind_gust <dbl>, precip <dbl>, pressure <dbl>,
    ## #   visib <dbl>, time_hour <dttm>

``` r
#display total number of rows in dataset
nrow(early_january_weather)
```

    ## [1] 358

``` r
#display total number of columns in dataset
ncol(early_january_weather)
```

    ## [1] 15

``` r
#finding mean for variable temp
mean(early_january_weather$temp)
```

    ## [1] 39.58212

``` r
#finding the sd for variable temp 
sd(early_january_weather$temp)
```

    ## [1] 7.058637

**Data set description:** This data set contains weather factors for the
first half of January 2013. It has 358 observations and 15 variables,
including dew point, humidity, wind characteristics, precipitation, and
pressure. The mean temperature for the first half of January 2013 was
39.58 degrees Fahrenheit with a standard deviation of 7.06.

**Creating scatter plot and saving graph**

``` r
#load ggplot2 library
library(ggplot2)

#making scatterplot using ggplot function 
scatter_plot <- ggplot(early_january_weather, aes(x = time_hour, y = temp, color = humid)) + 
  geom_point() +
  labs(
    x = "Time (Hours)",
    y = "Temperature",
    title = "Scatterplot of Temperature vs Time with Humidity Color Code"
  ) + 
  scale_color_gradient(low = "blue", high = "red") + 
  theme_minimal()

#print scatterplot 
print(scatter_plot)
```

![](p8105_hw1_nn2477_files/figure-gfm/unnamed-chunk-2-1.png)<!-- -->

``` r
#save scatter plot as png
ggsave("scatterplot.png", plot = scatter_plot)
```

    ## Saving 7 x 5 in image

**Scatter plot description:** there seems to be an overall positive
correlation, meaning that as time (hrs) increases, temperature also
increases as well. however, no clear trend is evident, indicating a weak
correlation between time and temperature

**Problem 2**

``` r
#creating new data frame
df = tibble(
  random_sample = rnorm(10), 
  log_vec = rnorm(10) > 0, 
  char_vec = c("A", "B", "C", "D", "E", "F", "G", "H", "I", "J"),
  fact_vec = factor(sample(1:3, 10, replace = TRUE), levels = 1:3, labels = c("Level_1", "Level_2", "Level_3"))
)

#checking to see if data frame is created correctly 
print(df)
```

    ## # A tibble: 10 × 4
    ##    random_sample log_vec char_vec fact_vec
    ##            <dbl> <lgl>   <chr>    <fct>   
    ##  1       -0.626  FALSE   A        Level_3 
    ##  2        0.620  TRUE    B        Level_2 
    ##  3       -0.290  TRUE    C        Level_1 
    ##  4        0.205  TRUE    D        Level_3 
    ##  5       -0.367  FALSE   E        Level_1 
    ##  6        0.510  FALSE   F        Level_1 
    ##  7        0.0509 FALSE   G        Level_1 
    ##  8       -2.86   FALSE   H        Level_2 
    ##  9       -0.724  FALSE   I        Level_3 
    ## 10        0.351  FALSE   J        Level_1
